Refactor staking
morph-l2/morph pull request #693
Opened 2024-12-30 08:17 UTC by SegueII

2025-03-16 06:13 UTC, velaandre commented
Me pones al tanto de favor de los cambios que propones mira+524681000609 por wats app

2025-03-17 06:27 UTC, velaandre reviewed
En dónde va mi perfil para pago

2025-03-17 06:27 UTC, velaandre commented on bindings/bin/distribute_deployed.hex
Oye$$$$quieres que lo apruebe
Cómo se retira el dinero

2025-03-17 06:28 UTC, velaandre approved these changes

2025-03-17 06:30 UTC, velaandre commented
I have a lot of work but I need you to explain to me.

2025-03-31 01:45 UTC, velaandre commented
Oye vato Mira la mera neta no sé mucho de programación pero sé que se estanquen son mis activos que están generando ganancias pero la neta la neta necesito hacer saber dónde va mi dirección o qué es lo que tengo que poner para que me lleguen esas ganancias y poder usarlas más que nada

2025-04-29 09:34 UTC, velaandre reviewed
Hello friend, look, excuse me, I just want you to explain to me. I understand quickly. Please explain to me so I know what I'm doing, what I'm authorizing.

2025-05-06 21:34 UTC, velaandre approved these changes

2025-05-09 07:58 UTC, velaandre approved these changes

2025-06-24 03:10 UTC, velaandre requested changes
Y

2025-06-24 03:10 UTC, velaandre approved these changes

2025-12-17 09:36 UTC, velaandre approved these changes

2026-04-13 07:29 UTC, chengwenxi commented
Expired

2026-04-13 07:29 UTC, closed without merging

2026-04-25 22:17 UTC, velaandre commented
I need help to remove the email recovery option from all platforms; everyone's money is at risk.

2026-04-25 22:19 UTC, velaandre commented
Sorry for neglecting this system. A Mexican man has been trying to kill me for two years now, and they've completely wiped out my memory, but I'm learning again. Thank you.

2026-04-25 22:21 UTC, velaandre commented
compartan

2026-05-21 06:32 UTC, velaandre approved these changes